### ISSUE TITLE
Backslash error

### ISSUE THREAD

**Issue by HACKER28012006** [sabamdarif/termux-desktop#12]
awk: cmd. line:1: {print \$2}
awk: cmd. line:1:        ^ backslash not last character on line

**Comment by sabamdarif** [comment]
what you trying do here ?
which command you run

**Comment by HACKER28012006** [comment]
When I start gui and connect to termux x11
It is showing that error

**Comment by sabamdarif** [comment]
Can you me the configuration you made 

Go to  `$PREFIX/etc/termux-desktop`

nano `configuration` 

And send what inside it

**Comment by sabamdarif** [comment]
Go to $PREFIX/bin
type nano tx11start
and try removing this two line
process_id=
kill "$process_id" > /dev/null 2>&1

and add this

process_id=$(ps -aux | grep '[x]fce4-screensaver' | awk '{print $2}')
kill "$process_id" > /dev/null 2>&1
