### ISSUE TITLE
gzip error

### ISSUE THREAD

**Issue by NoReplyUI5** [sabamdarif/termux-desktop#13]
Install Gui Desktop In Termux                                          code by @sabamdrif

Downloading icon.tar.gz...                                             ################################################################ 100.0%                                                                       [80.6KiB/s] [===================================================>] 100%                                                                       gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now                             ~ $

**Comment by sabamdarif** [comment]
which style ?

**Comment by NoReplyUI5** [comment]
> which style ?

XFCE
style number 2: Modern Style

**Comment by sabamdarif** [comment]
Fixed https://github.com/sabamdarif/termux-desktop/commit/94595ee706d20e67b2a012bae3af47f182f2f086
