### ISSUE TITLE
After Installation None of icon show on desktop with folder

### ISSUE THREAD

**Issue by Secondyou** [sabamdarif/termux-desktop#14]
(it's happened randomly)

**Comment by sabamdarif** [comment]
yes , it's a problem which i can find any fix yet , the only solution i found is to install a new icon theme

**Comment by Secondyou** [comment]
i know a solution btw i think try to make script install fallback into papirus icon theme instead? if it's failed to extract and install

**Comment by Secondyou** [comment]
(it's installable on pkg,apt or nala command)

**Comment by sabamdarif** [comment]
ok 

> i know a solution btw i think try to make script install fallback into papirus icon theme instead? if it's failed to extract and install

yes it will be a good idia , but the icons croupted not because of it failed to install or something

**Comment by sabamdarif** [comment]
also i onetime fix it another which work for me 
after a fresh install go to the icons folder and generate icon cache manually for each icon theme then start using the desktop

The main problem is something to do with the icon cache

**Comment by Secondyou** [comment]
okay another solution is install fallback icon theme then gen cache after it installed
i thikk it's great

**Comment by sabamdarif** [comment]
did you tried it ?

**Comment by sabamdarif** [comment]
currently i didn't have this problem so i can't tell if it will work or not
