### ISSUE TITLE
Wine 

### ISSUE THREAD

**Issue by WOOD6563** [sabamdarif/termux-desktop#18]
Mobox wine doesn't not work please fix it

**Comment by sabamdarif** [comment]
What not working

**Comment by WOOD6563** [comment]
When I click wine explorer nothing happens please fix this

**Comment by sabamdarif** [comment]
> When I click wine file nothing happens please fix this

Type `wine winecfg` and see what happening there

**Comment by sabamdarif** [comment]
Closing this due to not responding
