### ISSUE TITLE
only termux cli look script.

### ISSUE THREAD

**Issue by raaz2507** [sabamdarif/termux-desktop#21]
please add a script only for chage termux cli envirement . without intalling any desktop envirement , gpu exletion ect. 
only script for install zsh and other cli cusmization 
![Screenshot_2024-09-04-23-27-15-461_com termux](https://github.com/user-attachments/assets/99221558-421b-4f61-b5c4-b98614cc0141)

**Comment by sabamdarif** [comment]
you can do it manually
 
1st) for zsh run this :- `pkg install zsh git -y`
then
`wget https://raw.githubusercontent.com/sabamdarif/simple-linux-scripts/main/install-zsh.sh && bash install-zsh.sh` 

2nd ) for color :- backup old color scheme by 
`mv $HOME/.termux/colors.properties $HOME/.termux/colors.properties.bak`
then run
`wget -O $HOME/.termux/colors.properties https://raw.githubusercontent.com/sabamdarif/termux-desktop/main/other/colors.properties`

3rd) then back old motd by 
`mv $PREFIX/etc/motd $PREFIX/etc/motd.bak ; mv $PREFIX/etc/motd-playstore $PREFIX/etc/motd-playstore.bak ; mv $PREFIX/etc/motd.sh $PREFIX/etc/motd.sh.bak` 
then
`wget -O $PREFIX/etc/motd.sh https://raw.githubusercontent.com/sabamdarif/termux-desktop/main/other/motd.sh`
and
`echo "bash $PREFIX/etc/motd.sh" >> "$PREFIX/etc/termux-login.sh"`

now restart termux and it's done

**Comment by sabamdarif** [comment]
Script you requested :-  `wget https://raw.githubusercontent.com/sabamdarif/simple-linux-scripts/main/better-termux.sh && bash better-termux.sh`

**Comment by raaz2507** [comment]
Thnx for your efforts.
