### ISSUE TITLE
I can't run desktop with virgl

### ISSUE THREAD

**Issue by Ebbing999** [sabamdarif/termux-desktop#22]
vtest_client_dispatch_commands: client context created.
vrend_winsys_make_context_current: Error switching context: EGL_BAD_ACCESS
client: VTEST_CLIENT_DISCONNECTED
/data/data/com.termux/files/usr/bin/tx11start: line 26: 26076 Aborted                 env DISPLAY=:1.0 GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.0 dbus-launch --exit-with-session xfce4-session > /dev/null 2>&1

**Comment by sabamdarif** [comment]
Use zink
