### ISSUE TITLE
error while configure python3-minimal

### ISSUE THREAD

**Issue by NickoDPu** [sabamdarif/termux-desktop#23]
root@localhost:~# apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 python3 : PreDepends: python3-minimal (= 3.10.6-1~22.04) but 3.10.6-1~22.04.1 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
![Screenshot_2024-09-08-15-15-21-89](https://github.com/user-attachments/assets/c30b71b6-cb39-49bd-9779-e56ba4c1bb9c)

**Comment by NickoDPu** [comment]
i want to install xfce4 and tigervnc, then i input command "apt update -y && apt upgrade -y" then the error come out. please some one can fix it

**Comment by sabamdarif** [comment]
apt clean
apt --fix-broken install
dpkg --configure -a
sudo dpkg --force-all -i python3

**Comment by NickoDPu** [comment]
ok work 😁
