### ISSUE TITLE
Packages not installing

### ISSUE THREAD

**Issue by WormasterGpt** [sabamdarif/termux-desktop#24]
Packages not installing what the helll???!?!!?!

I want delete this utilit!!!
![Uploading Screenshot_20240914-102919_Termux.jpg…]()

**Comment by sabamdarif** [comment]
please perfectly upload the screenshot

**Comment by sabamdarif** [comment]
closing for not responding

**Comment by WormasterGpt** [comment]
> пожалуйста, загрузите скриншот правильно

I reinstalled termux
