### ISSUE TITLE
Screen black

### ISSUE THREAD

**Issue by solakcemalettin** [sabamdarif/termux-desktop#29]
![Screenshot_20241007-154316_TermuxX11.jpg](https://github.com/user-attachments/assets/0933a13f-5ef2-4d82-855d-d785e4d8b3a5)

**Comment by sabamdarif** [comment]
`tx11start --nogpu` try this

**Comment by solakcemalettin** [comment]
Same and showing this error ![Screenshot_20241007-164440_Termux.jpg](https://github.com/user-attachments/assets/1b0036f2-2b85-4093-8cc0-05e1b02b4791)

**Comment by sabamdarif** [comment]
Type `tdconfig` in termux and send me the part called device information

**Comment by solakcemalettin** [comment]
![Screenshot_20241008-133527_Termux.jpg](https://github.com/user-attachments/assets/074197f0-1aca-4008-a65a-2a12b434f1ca)

![Screenshot_20241008-133532_Termux.jpg](https://github.com/user-attachments/assets/9f365c47-349b-460c-96b0-0c1f381b4ecc)

**Comment by sabamdarif** [comment]
i don't know  it might be the problem of your cpu architecture

**Comment by daulatrathod** [comment]
Black screen 
![Screenshot_20241008_213106_TermuxX11](https://github.com/user-attachments/assets/6a2f9e3e-b3f4-4bd8-9ea1-b8b70f7c8ae7)

**Comment by daulatrathod** [comment]
tdconfig
![Screenshot_20241008_213200_Termux](https://github.com/user-attachments/assets/d3b6355a-7e36-46d1-a631-a1de6e807138)

**Comment by daulatrathod** [comment]
Pls gave help me same on vnc

**Comment by sfantu** [comment]
Try legacy drawing

**Comment by ginestopo** [comment]
I am facing the same issue...

**Comment by sabamdarif** [comment]
change ` XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :1.0 &` with `XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :1.0 -legacy-drawing &` in `$PREFIX/bin/tx11start` file

**Comment by ginestopo** [comment]
@sabamdarif thanks a lot! Another problem I am facing is:
**[Process completed (signal 9) - press Enter]**
It shuts down termux (and termux:x11) randomly due to a phantom killer present in Android 12.

Although this error is not related to your script. I failed to find a safe and easy fix. (Access to developer setting is not possible in my device, cause I am running it in Meta Quest 3). This makes termux unusable in Android 12.

**Comment by sabamdarif** [comment]
> @sabamdarif thanks a lot! Another problem I am facing is: **[Process completed (signal 9) - press Enter]** It shuts down termux (and termux:x11) randomly due to a phantom killer present in Android 12.
> 
> Although this error is not related to your script. I failed to find a safe and easy fix. (Access to developer setting is not possible in my device, cause I am running it in Meta Quest 3). This makes termux unusable in Android 12.

the method i knew that required usb debugging or wireless debugging or root to work

**Comment by sabamdarif** [comment]
fixed https://github.com/sabamdarif/termux-desktop/commit/9dd423601fec5ba1165e362d10d9b63a1b357899
