### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by pengyixq** [sabamdarif/termux-desktop#31]
安装过程中，有些链接无法获取，装上去后有些程序无法启动，能不能更新下安装代码呢

**Comment by sabamdarif** [comment]
which links and programs can you , can you describe it properly .

**Comment by pengyixq** [comment]
Thank you for your update and improvement. The previous issue has been resolved, but now I have found another problem. The software installed in Debian cannot be started on the Termux desktop without any response. I don't know the reason.



---原始邮件---
发件人: "Md ***@***.***&gt;
发送时间: 2024年11月16日(周六) 中午12:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sabamdarif/termux-desktop] 安装失败 (Issue #31)




 
Closed #31 as completed.

**Comment by sabamdarif** [comment]
> Thank you for your update and improvement. The previous issue has been resolved, but now I have found another problem. The software installed in Debian cannot be started on the Termux desktop without any response. I don't know the reason.
> […](#)
> ---原始邮件--- 发件人: "Md ***@***.***&gt; 发送时间: 2024年11月16日(周六) 中午12:25 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [sabamdarif/termux-desktop] 安装失败 (Issue #31) Closed #31 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

join the telegram channel
