### ISSUE TITLE
Virgl error on any desktop

### ISSUE THREAD

**Issue by ONENAMED** [sabamdarif/termux-desktop#33]
``ERR: renderergl_utils.cpp:3057 (HandleError): GL call functions->texImage2D(nativegl::GetTextureBindingTarget(target), static_cast<GLint>(level), texImageFormat.internalFormat, size.width, size.height, 0, texImageFormat.format, texImageFormat.type, pixels) generated error 0x00000502 in ../../../cache/tmp-checkout/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:276.
ERR: renderergl_utils.cpp:3057 (HandleError): GL call functions->texImage2D(nativegl::GetTextureBindingTarget(target), static_cast<GLint>(level), texImageFormat.internalFormat, size.width, size.height, 0, texImageFormat.format, texImageFormat.type, pixels) generated error 0x00000502 in ../../../cache/tmp-checkout/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:276.
ERR: renderergl_utils.cpp:3057 (HandleError): GL call functions->texImage2D(nativegl::GetTextureBindingTarget(target), static_cast<GLint>(level), texImageFormat.internalFormat, size.width, size.height, 0, texImageFormat.format, texImageFormat.type, pixels) generated error 0x00000502 in ../../../cache/tmp-checkout/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:276.
ERR: renderergl_utils.cpp:3057 (HandleError): GL call functions->texImage2D(nativegl::GetTextureBindingTarget(target), static_cast<GLint>(level), texImageFormat.internalFormat, size.width, size.height, 0, texImageFormat.format, texImageFormat.type, pixels) generated error 0x00000502 in ../../../cache/tmp-checkout/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:276.
ERR: renderergl_utils.cpp:3057 (HandleError): GL call functions->texImage2D(nativegl::GetTextureBindingTarget(target), static_cast<GLint>(level), texImageFormat.internalFormat, size.width, size.height, 0, texImageFormat.format, texImageFormat.type, pixels) generated error 0x00000502 in ../../../cache/tmp-checkout/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:276.
ERR: renderergl_utils.cpp:3057 (HandleError): GL call functions->texImage2D(nativegl::GetTextureBindingTarget(target), static_cast<GLint>(level), texImageFormat.internalFormat, size.width, size.height, 0, texImageFormat.format, texImageFormat.type, pixels) generated error 0x00000502 in ../../../cache/tmp-checkout/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:276.
vtest_client_dispatch_commands: client context created.
vrend_winsys_make_context_current: Error switching context: EGL_BAD_ACCESS

> bruh

**Comment by sabamdarif** [comment]
fixed https://github.com/sabamdarif/termux-desktop/commit/47a028fcf26aa63e5b4ec3045a04a84e6270f7cf uninstall everything and try agin
