### ISSUE TITLE
Error when i type wine winecfg

### ISSUE THREAD

**Issue by Yamak5** [sabamdarif/termux-desktop#39]
How can i run exe ?
It gave me error when i type wine winecfg 
Like that :
wine winecfg
/data/data/com.termux/files/usr/bin/wine: line 52: /data/data/com.termux/files/usr/glibc/opt/package-manager/token: No such file or directory
/data/data/com.termux/files/usr/bin/wine: line 81: /data/data/com.termux/files/usr/glibc/opt/scripts/configs: No such file or directory
/data/data/com.termux/files/usr/bin/wine: line 82: load_configs: command not found
chmod: cannot access '/data/data/com.termux/files/usr/glibc/bin/box64': No such file or directory
chmod: cannot access '/bin/wine': No such file or directory
chmod: cannot access '/bin/wineserver': No such file or directory
/data/data/com.termux/files/usr/bin/wine: line 97: patchelf: command not found
ln: failed to create symbolic link '/data/data/com.termux/files/usr/glibc/bin/wine': No such file or directory
ln: failed to create symbolic link '/data/data/com.termux/files/usr/glibc/bin/wineserver': No such file or directory
cp: cannot stat '/data/data/com.termux/files/usr/glibc/opt/prefix/start/Registry/2.*': No such file or directory
cp: cannot stat '/data/data/com.termux/files/usr/glibc/opt/prefix/start/Install/media foundation (for RE).lnk': No such file or directory
mkdir: cannot create directory ‘/moboxmeta’: Read-only file system
Applying services fix
touch: cannot touch '/moboxmeta/services-fix-applied': No such file or directory
Applying fonts fix
tar: /data/data/com.termux/files/usr/glibc/opt/prefix/fix-fonts.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
touch: cannot touch '/moboxmeta/fonts-fix-applied': No such file or directory
Applying dlls fix
touch: cannot touch '/moboxmeta/dxdlls-fix-applied': No such file or directory
/data/data/com.termux/files/usr/bin/wine: line 157: load_configs: command not found
taskset: failed to parse CPU list: /data/data/com.termux/files/usr/glibc/bin/box64

How can i fix it :(
![Screenshot_20241110-161553](https://github.com/user-attachments/assets/c1fbc8d6-6625-4494-a766-ffcc283c3805)

**Comment by sabamdarif** [comment]
try reinstalling mobox, after reinstalling mobox launch it once using mobox command

**Comment by Yamak5** [comment]
When i type mobox in terminal that's happen :
![Screenshot_20241110-164516.png](https://github.com/user-attachments/assets/a45bb77f-380a-461c-8cfe-598b83ea24a6)






And i wait a little the this happen :


![Screenshot_20241110-164526.png](https://github.com/user-attachments/assets/48c5c201-995e-4fea-a209-4d9bf1cd3da1)

**Comment by sabamdarif** [comment]
bro type mobox command in termux terminal (no need to do it now , what you did is also fine) not in the desktop now stop termux x11(type tx11stop -f  in termux) then start termux desktop and run winecfg

**Comment by Yamak5** [comment]
Everything is fine now !
Thank You So much :)

**Comment by Yamak5** [comment]
Does Virgl zink support Mali GPU or only Adreno
And what about Virgl does support Mali?

And the VirGL Render run in apps and firefox and games automatically when i open them or i need to type some codes to run them in VirGL or they will run in llvmpipe automatically ?

**Comment by gurachan** [comment]
> bro type mobox command in termux terminal (no need to do it now , what you did is also fine) not in the desktop now stop termux x11(type tx11stop -f in termux) then start termux desktop and run winecfg

I did that but still no wine..

**Comment by sabamdarif** [comment]
> > bro type mobox command in termux terminal (no need to do it now , what you did is also fine) not in the desktop now stop termux x11(type tx11stop -f in termux) then start termux desktop and run winecfg
> 
> I did that but still no wine..

with mobox ?
did you start mobox once before starting it in the desktop ?
