### ISSUE TITLE
No easy way to uninstall the desktop 

### ISSUE THREAD

**Issue by arjunshinoj** [sabamdarif/termux-desktop#4]
Maybe there is a super obvious way to uninstall this. But I couldn't find it

**Comment by sabamdarif** [comment]
apt autoremove xfce* xwayland kvantum gnome-themes-extra -y
rm -rf $HOME/.themes $HOME/.config" $HOME/.icons

this will do 

i will add the uninstall option in next update , 
Thank's for suggestion

**Comment by sabamdarif** [comment]
If you find anything else is missing let me know 👍

**Comment by sabamdarif** [comment]
remove option added

**Comment by arjunshinoj** [comment]
> remove option added

That's great 👍 sorry I didn't check in afterwards
