### ISSUE TITLE
Error Render in VirGL Zink for (Mali-g52)

### ISSUE THREAD

**Issue by Yamak5** [sabamdarif/termux-desktop#40]
Does Virgl zink support Mali-g52 GPU or only Adreno
And what about Virgl does support Mali?

And the VirGL Render run in apps and firefox and games automatically when i open them or i need to type some codes to run them in VirGL or they will run in llvmpipe automatically ?

I got this evey time i open Termux gui 

![Screenshot_20241111-025218~2](https://github.com/user-attachments/assets/e401e4db-9c08-4b4f-ba61-0a26b8e41635)

**Comment by sabamdarif** [comment]
it have no fix for now just wait until termux team fix it

**Comment by Yamak5** [comment]
So I understand from you that there is no freegel supporting my money

**Comment by Yamak5** [comment]
So, I understand from you that there are no Mesa drivers, like VirGL, that support the Mali GPU."

**Comment by sabamdarif** [comment]
> So, I understand from you that there are no Mesa drivers, like VirGL, that support the Mali GPU."

Some mali gpu suppot some not
