### ISSUE TITLE
Make a telegram or discord server for support, github is inconsistent.

### ISSUE THREAD

**Issue by Awashit** [sabamdarif/termux-desktop#44]
Provide their links on this repo.

**Comment by sabamdarif** [comment]
Ok i will create a telegram group soon

**Comment by Awashit** [comment]
Umm hardware acceleration doesn't seem to work other than virgl on my mali device, is there any way to hardware acceleration with virgl zink with firefox?

**Comment by sabamdarif** [comment]
did you tried Experimental GPU Drivers ?

**Comment by Awashit** [comment]
Yeah i tried those too is there some code i need to run before in order to enable hardware acceleration in firefox and chromium

**Comment by Awashit** [comment]
My device is samsung tablet a9
Its pretty mid

**Comment by sabamdarif** [comment]
> Yeah i tried those too is there some code i need to run before in order to enable hardware acceleration in firefox and chromium

enable webgl

**Comment by Awashit** [comment]
Did it work for you on your mali device
Do i need to enable webgl.disabled to false and webgl force enabled to true in about config?
I will try today and inform you situation

**Comment by Awashit** [comment]
![Screenshot_20241115_090127_TermuxX11](https://github.com/user-attachments/assets/63cada6a-e4b1-48c3-8e19-a9d56b9b2071)
![Screenshot_20241115_090102_TermuxX11](https://github.com/user-attachments/assets/72eb8023-7aba-4221-871e-85f058bf0bed)
![Screenshot_20241115_090036_TermuxX11](https://github.com/user-attachments/assets/6bb4174e-83d3-467d-a85f-23e6efb1f864)
![Screenshot_20241115_090001_TermuxX11](https://github.com/user-attachments/assets/54c40cec-e594-4e10-aacb-f024571332f9)
![Screenshot_20241115_085905_TermuxX11](https://github.com/user-attachments/assets/58f79add-e75a-41fb-8437-31ae5b5ee095)

**Comment by Awashit** [comment]
Virgl-zink too didnt work

**Comment by Awashit** [comment]
Only virgl seems to work

**Comment by sabamdarif** [comment]
Experimental GPU Drivers have only support for vulkan thats why it didn't work

**Comment by Awashit** [comment]
Currently no hardware acceleration works including viral
It seems they only work on lxqt

**Comment by sabamdarif** [comment]
https://t.me/hello_android_0 join me here
