### ISSUE TITLE
Wine 🍷

### ISSUE THREAD

**Issue by WOOD6563** [sabamdarif/termux-desktop#48]
I set up mobox after installing termux-desktop but still the wine file is not working

**Comment by WOOD6563** [comment]
Ok but did you have discord ?

**Comment by WOOD6563** [comment]
Hmm  What, I'm starting Mobox but still termux dekstop was running in x11

**Comment by sabamdarif** [comment]
> Hmm What, I'm starting Mobox but still termux desktop was running in x11

watch this video:- https://youtu.be/4vytIzyQa-4

**Comment by WOOD6563** [comment]
Then  ?

**Comment by sabamdarif** [comment]
> Then ?

after installation does it launch, like how it launch in the video

**Comment by WOOD6563** [comment]
Bro close this issue I fix it
