### ISSUE TITLE
Chinese and the input method for Chinese

### ISSUE THREAD

**Issue by 2061360308** [sabamdarif/termux-desktop#50]
How can I set the system language to Chinese and how can I add a Chinese input method? I want to use fcitx.

**Comment by darkwebdisclaimer** [comment]
### `how to fix issues my firefox keep on closing by it self`

# my android detiels

* System Info:
* System          :   Android 12
* Host            :   Itel itel A662L
* Kernel          :   Linux 5.4.233+-ab701
* CPU             :   Spreadtrum SC9832E (4 vCPU)
* Termux Version  :   0.119.0-beta.1-
* Memory          :   909Mi used, 1.9Gi total
* Temperature     :   °c

**Comment by sabamdarif** [comment]
> ### `how to fix issues my firefox keep on closing by it self`
> # my android detiels
> 
>     * System Info:
> 
>     * System          :   Android 12
> 
>     * Host            :   Itel itel A662L
> 
>     * Kernel          :   Linux 5.4.233+-ab701
> 
>     * CPU             :   Spreadtrum SC9832E (4 vCPU)
> 
>     * Termux Version  :   0.119.0-beta.1-
> 
>     * Memory          :   909Mi used, 1.9Gi total
> 
>     * Temperature     :   °c

might be gpu issue / ram issue

**Comment by sabamdarif** [comment]
> How can I set the system language to Chinese and how can I add a Chinese input method? I want to use fcitx.

https://ivonblog.com/en-us/posts/termux-x11/#7-how-to-type-chinse-in-termux-x11
