### ISSUE TITLE
How termux-desktop realize pdrun exactly?

### ISSUE THREAD

**Issue by shadowquark** [sabamdarif/termux-desktop#52]
Hi,

Bravo my friends! Your work is pretty awesome. I am trying to configure my realization of your work piece by piece, instead of setting altogether following your script.

Now I am curious how you realize the pdrun to run a program from proot-distro (eg. debian) in termux-x11 together with termux apps.

Best wishes
Zhongyi

**Comment by sabamdarif** [comment]
in setup script there is a line called 
proot-distro login --user $final_user_name $selected_distro --shared-tmp -- eval "env DISPLAY=:1.0 XDG_RUNTIME_DIR=\${TMPDIR} \$selected_pd_hw_method \$@"

the $selected_distro change according to what distro you chose and the $@ is = the program execute command
