### ISSUE TITLE
New user isn't existed in proot-distro's /etc/passwd & Running commands in proot-distro's terminal shows cannot found libld.so

### ISSUE THREAD

**Issue by MCredbear** [sabamdarif/termux-desktop#6]
I don't know if this is normal, and I open proot-distro's terminal by `debian` , `tx11start`, then open terminal in termux-x11

**Comment by sabamdarif** [comment]
where did you type the tx11start command inside debian or inside termux ?

**Comment by sabamdarif** [comment]
and for libld.so , i think it's problem of debian installation the debian (proot distro) installation might corrupted in the process

**Comment by MCredbear** [comment]
> where did you type the tx11start command inside debian or inside termux ?

in proot debian

**Comment by MCredbear** [comment]
> and for libld.so , i think it's problem of debian installation the debian (proot distro) installation might corrupted in the process

it is strange that, just run commands after `debian` in proot CLI works fine, but in the desktop terminal after `tx11start` in proot CLI, this occurs

**Comment by sabamdarif** [comment]
> tx11start

the `tx11start` is for termux itself not for debian

**Comment by MCredbear** [comment]
> > tx11start
> 
> the `tx11start` is for termux itself not for debian

So the correct way to run proot app is to run `pdrun [COMMAND]` in termux itself's desktop's terminal? Termux and proot sharing the same `bin` and `$PATH` confuses me....

**Comment by sabamdarif** [comment]
Yes

**Comment by sabamdarif** [comment]
for the _/etc/passwd_ issue , login into debian `pd login debian`  and type `passwd username`

**Comment by MCredbear** [comment]
> for the _/etc/passwd_ issue , login into debian `pd login debian` and type `passwd username`

I typed `adduser username` after logined which also fixes it, but no idea whether it causes new issues

**Comment by sabamdarif** [comment]
what issue ?

**Comment by MCredbear** [comment]
> what issue ?

currently nope

**Comment by MCredbear** [comment]
My SoC is Qcom 8gen1 , I chose turnip driver for proot debian, but when I run `pdrun glxgears -info`, it shows llvmpip driver, then I run `pdrun sudo apt install mesa-utils` and rerun `pdrun glxgears -info`, it it shows 
```
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
libGL error: glx failed to create drisw screen
libGL error: failed to load driver: zink
Error: glXCreateContext failed
```

**Comment by MCredbear** [comment]
Another question: If I want to open a proot directory in code-oss, what should I do?

**Comment by sabamdarif** [comment]
> pdrun sudo apt install mesa-utils

don't use `pdrun sudo apt install mesa-utils` insted use `debian install mesa-utils`
i think you didn't read all documentation

and for error: XDG_RUNTIME_DIR is invalid or not set in the environment i have to look for it

**Comment by sabamdarif** [comment]
> Another question: If I want to open a proot directory in code-oss, what should I do?



> Another question: If I want to open a proot directory in code-oss, what should I do?

the Desktop, Music, Downloads, Pictures and Videos folders of the proot-distro are link with the termux home directory's folders

**Comment by sabamdarif** [comment]
> > Another question: If I want to open a proot directory in code-oss, what should I do?
> 
> > Another question: If I want to open a proot directory in code-oss, what should I do?
> 
> the Desktop, Music, Downloads, Pictures and Videos folders of the proot-distro are link with the termux home directory's folders

if you create any new folder in proot-distro's home directory if have open it manuanny but i will add the option soon

**Comment by MCredbear** [comment]
> > pdrun sudo apt install mesa-utils
> 
> don't use `pdrun sudo apt install mesa-utils` insted use `debian install mesa-utils` i think you didn't read all documentation

sorry, but
![Screenshot_20240611_134856_TermuxX11](https://github.com/sabamdarif/termux-desktop/assets/40625974/99366d8a-066f-4d94-b949-420b41578647)

**Comment by sabamdarif** [comment]
It can't handle .deb file now

And also vs code natively available it termux

**Comment by MCredbear** [comment]
> It can't handle .deb file now
> 
> And also vs code natively available it termux

But how can I use some vscode plugins that require toolchains in proot, such as gdb and dart, these plugins need to launch the binaries in proot

**Comment by sabamdarif** [comment]
> > It can't handle .deb file now
> > And also vs code natively available it termux
> 
> But how can I use some vscode plugins that require toolchains in proot, such as gdb and dart, these plugins need to launch the binaries in proot

first login into debian
then run this on debian
`curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`
`sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/keyrings/microsoft-archive-keyring.gpg`
`sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'`

`sudo apt-get update`

logout from debian

in termux type `debian install code`

i think it will help you to install vscode

**Comment by sabamdarif** [comment]
First login into debian then run

`sudo apt update`
`sudo apt install gnupg2 software-properties-common apt-transport-https curl`
`curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -`
`sudo add-apt-repository "deb [arch=arm64] https://packages.microsoft.com/repos/vscode stable main"
`
change the `arm64` according to your system like:- `amd64`,`armhf`

`sudo apt update`

logout from debian

`debian install code`

i think it will help you to install vscode

**Comment by sabamdarif** [comment]
also for ls command install lsd in debian

**Comment by MCredbear** [comment]
> First login into debian then run
> 
> `sudo apt update` `sudo apt install gnupg2 software-properties-common apt-transport-https curl` `curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -` `sudo add-apt-repository "deb [arch=arm64] https://packages.microsoft.com/repos/vscode stable main" ` change the `arm64` according to your system like:- `amd64`,`armhf`
> 
> `sudo apt update`
> 
> logout from debian
> 
> `debian install code`
> 
> i think it will help you to install vscode

OK, succeeded to install and add it to menu, but no luck to run it, sad

**Comment by sabamdarif** [comment]
> > First login into debian then run
> > `sudo apt update` `sudo apt install gnupg2 software-properties-common apt-transport-https curl` `curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -` `sudo add-apt-repository "deb [arch=arm64] https://packages.microsoft.com/repos/vscode stable main" ` change the `arm64` according to your system like:- `amd64`,`armhf`
> > `sudo apt update`
> > logout from debian
> > `debian install code`
> > i think it will help you to install vscode
> 
> OK, succeeded to install and add it to menu, but no luck to run it, sad

type `pdrun code` and see what's the error

**Comment by MCredbear** [comment]
> > > First login into debian then run
> > > `sudo apt update` `sudo apt install gnupg2 software-properties-common apt-transport-https curl` `curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -` `sudo add-apt-repository "deb [arch=arm64] https://packages.microsoft.com/repos/vscode stable main" ` change the `arm64` according to your system like:- `amd64`,`armhf`
> > > `sudo apt update`
> > > logout from debian
> > > `debian install code`
> > > i think it will help you to install vscode
> > 
> > 
> > OK, succeeded to install and add it to menu, but no luck to run it, sad
> 
> type `pdrun code` and see what's the error

![Screenshot_20240613_111449_TermuxX11](https://github.com/sabamdarif/termux-desktop/assets/40625974/be40361f-c5a2-4f79-bcae-5d185dde476b)
it detached the shell

**Comment by sabamdarif** [comment]
i think vscode isn't installed , login into debian and run `code` command

**Comment by MCredbear** [comment]
> i think vscode isn't installed , login into debian and run `code` command

![Screenshot_20240613_205156_TermuxX11](https://github.com/sabamdarif/termux-desktop/assets/40625974/2d5bf26c-8074-4f8c-8cfd-893941daa801)

**Comment by sabamdarif** [comment]
check if `xorg-xhost` installed or not in termux

**Comment by MCredbear** [comment]
> check if `xorg-xhost` installed or not in termux

![Screenshot_20240614_104709_Termux](https://github.com/sabamdarif/termux-desktop/assets/40625974/0ace1f61-346d-47d4-a420-e895908a7375)
Yes, bro

**Comment by sabamdarif** [comment]
as for the vscode doesn't run in debian all you need to do just run it with `--no-sandbox` flag it sould work
