### ISSUE TITLE
./setup-termux-desktop

### ISSUE THREAD

**Issue by xnnnsets** [sabamdarif/termux-desktop#7]
./setup-termux-desktop
./setup-termux-desktop: line 663: syntax error near unexpected token `}'
./setup-termux-desktop: line 663: `}'

**Comment by sabamdarif** [comment]
sorry i didn't test it that time , it fixed now https://github.com/sabamdarif/termux-desktop/commit/c8109ca5ff063876532bc8b16b9ec3eae1781d26
