### ISSUE TITLE
stdn: not in gzip format 

### ISSUE THREAD

**Issue by devanshyadav2010** [sabamdarif/termux-desktop#9]
After installing and while downloading icon.tar.gz 100%
It is showing an error
![20240622_233911](https://github.com/sabamdarif/termux-desktop/assets/108845911/b9309e86-3490-422f-a7ed-e5ee7205163c)

**Comment by sabamdarif** [comment]
which style ?

**Comment by devanshyadav2010** [comment]
Modern Style

**Comment by devanshyadav2010** [comment]
> which style ?

Modern Style

**Comment by sabamdarif** [comment]
fixed 720cc83f979e0ecb52d489c8e16dd586c2949be9
